apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.service.name }}
  labels:
    release: {{ .Release.Name }}
    {{- toYaml .Values.web.service.labels | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.web.port }}
    targetPort: 80
    protocol: TCP
    name: nginx
  - port: {{ .Values.web.sslPort }}
    targetPort: 443
    protocol: TCP
    name: nginx-ssl
  type: ClusterIP
  selector:
    {{- toYaml .Values.web.serviceSelectorLabels | nindent 4 }}
